version: '2'
services:
  helloworld:
    build: .
    ports:
    - "8080:8080"
    - "62911:62911"
    - "8849:8849"
    volumes:
    - "$PWD/logs:/usr/local/tomcat/logs"
    environment:
      CATALINA_OPTS:  "-Dcom.sun.management.jmxremote.rmi.port=9090 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=9090 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=172.28.220.207 -agentlib:jdwp=transport=dt_socket,address=62911,server=y,suspend=n"
